### ISSUE TITLE
Drop Puppet 3 support.

### ISSUE THREAD

**Issue by jkroepke** [voxpupuli/puppet-gitlab#118]
Hi,

i want to ask, if its possible to drop puppet 3 support in the next time.

I would like to create a PR to replace all deprecated `validate_*` functions with puppet 4 data type validation. I also want to replace deprecated `hiera` function with the new lookup function.

**Comment by tobru** [comment]
Feel free to open a PR

**Comment by tobru** [comment]
Thanks for your work on the PR! We'd like to keep Puppet 3 support for a while available, there are many existing Puppet 3 infrastructures around which are not yet upgraded to 4. I guess in a few months we can drop Puppet 3 support. We'll keep this issue open to not forget about it and work on it as soon as possible.

**Comment by jkroepke** [comment]
@tobru I can understand you, but puppet 3 users can still use an older version of this module. Also voxpupuli and puppetlabs itself drops puppet 3 already, for example see the lastest version of concat.

**Comment by jkroepke** [comment]
@tobru Any updates about the movement to puppet 4?

Puppet 5 is out most of all offical module and voxpopuli modules drop puppet 3 already. 

Puppet 3 users can still used old versions of this module.

**Comment by timhughes** [comment]
@jkroepke Having this module support puppet3 is useful for all those using it and attempting to move to puppet4/5. Gitlab and all the functionallity it has/is adding is making this job of moving easier. Not being able to take advantage of new features would be disapointing.

**Comment by jkroepke** [comment]
@timhughes Maybe I miss to understand you but I don't see it why it would be make easier to move because this module have puppet 3 support.

If this module had already drop puppet 3 support, you can do your case too by using the latest version of this module that support puppet 3.

**Comment by LongLiveCHIEF** [comment]
Closed with 2924d09a32b7a5bf3b3933fe2a1940c889e12a03

> Having this module support puppet3 is useful for all those using it and attempting to move to puppet4/5. Gitlab and all the functionallity it has/is adding is making this job of moving easier. Not being able to take advantage of new features would be disapointing.

@timhughes I understand this scenario very well, as I'm going through this situation myself.  In the end, your argument for keeping Puppet 3 support is the same argument for _dropping_ Puppet 3 support. There are many features with Puppet 4 that it was adding difficulty not being able to take advantage of, and dropping Puppet 3 support and embracing Puppet 4 makes it easier for us to maintain this module, and makes it easier for contributors to make a contribution since it now requires far less code.

The major part of this module is the `template/gitlab.rb.erb`, which at this point and time is still compatible with Puppet 3, giving users still on Puppet 3 an option to just keep your own fork of this module from an old version up to date with patches to `template/gitlab.rb.erb`.

I will be adding HA support to this module in the near future, and have no plans that would make the `templates/gitlab.rb.erb` incompatible with Puppet 3 at this time. If you still need to support Puppet 3, my recommendation would be to fork this module from the latest release that works on your system, and then patch in updates to the template, adding any new keys to your own `manifests/init.pp` and `manifests/config.pp`.

I hope you can update your puppet infrastructure soon, but until then, If you need help applying any given patch in the future, hit me up by [joining the Puppet Communi Slack channel](https://slack.puppet.com/) and sending me a DM.
