### ISSUE TITLE
data dir changes in gitlab 9

### ISSUE THREAD

**Issue by logicminds** [voxpupuli/puppet-gitlab#137]
I believe gitlab changed the hash for data dirs again in 9.0.  So I think we will need to update the code here.  This is additional path attribute with the hash.

Not sure if legacy configs will work or if the path key is required if a path is provided instead of a hash.

Assuming the extra hash is for further configurations when using nfs, cephfs.

https://github.com/vshn/puppet-gitlab/blob/master/manifests/config.pp#L18

```ruby
git_data_dirs({
  "default" => { "path" => "/var/opt/gitlab/git-data" },
  "nfs" => { "path" => "/mnt/nfs/git-data" },
  "cephfs" => { "path" => "/mnt/cephfs/git-data" }
})
```

ref: https://docs.gitlab.com/ce/administration/repository_storage_paths.html

**Comment by tobru** [comment]
Would you mind to create a PR for this change? Would be great!

**Comment by LongLiveCHIEF** [comment]
I've confirmed with Gitlab support that the legacy formatting is still supported. they had a discrepancy in their docs vs their template file, and I have an issue logged to fix this: https://gitlab.com/gitlab-org/gitlab-ee/issues/4040.

Since our existing template will create both formats successfully, no changes are needed.
