### ISSUE TITLE
Please set vm.overcommit_memory = 1 for redis to avoid problems in low free memory conditions

### ISSUE THREAD

**Issue by gdubicki** [voxpupuli/puppet-gitlab#144]
To avoid problems such as https://gitlab.com/gitlab-org/gitlab-ce/issues/26683 please set vm.overcommit_memory = 1 in sysctl for redis embedded in GitLab.

**Comment by davidgubler** [comment]
Because this is a global setting, I am currently not convinced that it should be done in the base module:
* Adds a dependency to a sysctl puppet module (which one should we use?)
* Causes duplicate resource issues if the setting is also required by some other module on the same system

As a workaround, https://github.com/thias/puppet-sysctl can be used from Hiera or directly from a Puppet module.
