### ISSUE TITLE
`decorate` method in `templates/gitlab.rb.erb` file may break some thing

### ISSUE THREAD

**Issue by yasserzamani** [voxpupuli/puppet-gitlab#146]
For example:
`gitlab_rails => {smtp_password => '12345'}`
generates
`gitlab_rails['smtp_password'] = 12345`
which is wrong because password is a string not number and this does not work in sending email (throws an exception)!

**Comment by davidgubler** [comment]
I think the decorate() method is only needed in its current form because of Puppet 3's broken type handling (Puppet 3 converts integers to strings in some cases where it shouldn't). Thus I think we can improve it once we drop Puppet 3 support (which, unfortunately, we can't do just yet - but it's in progress).
