### ISSUE TITLE
2.1.1 should be 3.0.0

### ISSUE THREAD

**Issue by roidelapluie** [voxpupuli/puppet-gitlab#236]
I am concerned that it is a 2.x release while the version in the meadata.json stqted 3.0.0.

Why is that? Looks like some types have changed.

**Comment by LongLiveCHIEF** [comment]
It's correct as is. I originally wasn't going to add a deprecation for `skip_auto_migrations`, and just entirely remove it.   However, I decided it was best to leave it in there so that we could continue to support older versions of gitlab, and I just added a deprecation notice in the client catalog output.

As a result of this, there were no breaking changes, so I incremented the minor version instead of the major version. (I forgot to drop the version in my original PR after adding the deprecation, so that PR was accepted with the metadata.json 3.0.0-rc0 version).

**Comment by roidelapluie** [comment]
Thanks
